import AppKit
import CryptoKit
import Darwin
import Foundation

// One-shot, public metadata lookup used at capture start. It identifies the
// currently running Ampersand application without reading input or changing
// application, cursor, or window state.

let expectedBundleIdentifier = "com.crossinput.Ampersand"
let candidates = NSWorkspace.shared.runningApplications.filter { application in
    application.bundleIdentifier == expectedBundleIdentifier
        || application.localizedName == "Ampersand"
        || application.executableURL?.lastPathComponent == "Ampersand"
}
let uniqueCandidates = Dictionary(grouping: candidates, by: { $0.processIdentifier })
    .compactMap { $0.value.first }
guard uniqueCandidates.count == 1,
      let application = uniqueCandidates.first,
      let bundleURL = application.bundleURL,
      let executableURL = application.executableURL else {
    fputs("expected exactly one running Ampersand application\n", stderr)
    exit(2)
}

let info = Bundle(url: bundleURL)?.infoDictionary ?? [:]
func infoString(_ keys: [String]) -> String? {
    for key in keys {
        if let value = info[key] as? String, !value.isEmpty {
            return value
        }
    }
    return nil
}

let bundleIdentifier = application.bundleIdentifier
    ?? infoString(["CFBundleIdentifier"])
let shortVersion = infoString(["CFBundleShortVersionString"])
let bundleVersion = infoString(["CFBundleVersion"])
guard let bundleIdentifier, !bundleIdentifier.isEmpty,
      let shortVersion, !shortVersion.isEmpty,
      let bundleVersion, !bundleVersion.isEmpty else {
    fputs("running Ampersand is missing required bundle identity fields\n", stderr)
    exit(2)
}

// A packaged app may contain a build-time candidate identifier generated by
// scripts/package-macos.sh. Preserve it only when it is explicitly exposed as
// bundle metadata. It is secondary metadata, not the executable identity.
let embeddedSourceSHA = infoString([
    "CrossInputSourceSHA", "CandidateIdentifier", "SCMRevision", "GitCommit",
])
guard let executableData = try? Data(contentsOf: executableURL) else {
    fputs("running Ampersand executable cannot be read for SHA-256 identity\n", stderr)
    exit(2)
}
let executableSHA256 = SHA256.hash(data: executableData)
    .map { String(format: "%02x", $0) }
    .joined()

let value: [String: Any] = [
    "schema": 1,
    "resolved": true,
    "pid": application.processIdentifier,
    "process_name": application.localizedName ?? "Ampersand",
    "bundle_identifier": bundleIdentifier,
    "bundle_short_version": shortVersion,
    "bundle_version": bundleVersion,
    "bundle_path": bundleURL.path,
    "executable_path": executableURL.path,
    "executable_sha256": executableSHA256,
    "crossinput_source_sha": embeddedSourceSHA ?? "unknown",
    "crossinput_build_identifier": infoString([
        "CrossInputBuildIdentifier", "BuildIdentifier",
    ]) ?? "unknown",
]
guard JSONSerialization.isValidJSONObject(value),
      let data = try? JSONSerialization.data(withJSONObject: value, options: [.sortedKeys]),
      let output = String(data: data, encoding: .utf8) else {
    exit(3)
}
print(output)
